install:
  - npm install

before_script:
  - npm run lint

script:
  - npm run build

before_deploy:
  - npm run test

deploy:
  provider: npm
  email: "eirik@archivedworks.com"
  api_key: $NPM-TOKEN
  on:
    branch: master